PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE INNOVSET(
INNOV INT PRIMARY KEY NOT NULL,
BASE INT NOT NULL,
TARGET INT NOT NULL
);
INSERT INTO "INNOVSET" VALUES(3,2,0);
INSERT INTO "INNOVSET" VALUES(6,3,1);
INSERT INTO "INNOVSET" VALUES(7,4,0);
INSERT INTO "INNOVSET" VALUES(1,5,3);
INSERT INTO "INNOVSET" VALUES(0,5,2);
INSERT INTO "INNOVSET" VALUES(8,4,1);
INSERT INTO "INNOVSET" VALUES(4,2,1);
INSERT INTO "INNOVSET" VALUES(2,5,4);
INSERT INTO "INNOVSET" VALUES(5,3,0);
CREATE TABLE TestNN_NODE(ID INT PRIMARY KEY NOT NULL, NODETYPE TEXT NOT NULL);
INSERT INTO "TestNN_NODE" VALUES(4,'HS');
INSERT INTO "TestNN_NODE" VALUES(5,'OS');
INSERT INTO "TestNN_NODE" VALUES(2,'HS');
INSERT INTO "TestNN_NODE" VALUES(0,'I');
INSERT INTO "TestNN_NODE" VALUES(1,'I');
INSERT INTO "TestNN_NODE" VALUES(3,'HS');
CREATE TABLE TestNN_CONN( INNOV INT PRIMARY KEY NOT NULL,
BASE INT NOT NULL,
TARGET INT NOT NULL,
WEIGHT REAL NOT NULL);
INSERT INTO "TestNN_CONN" VALUES(7,4,0,-0.3);
INSERT INTO "TestNN_CONN" VALUES(8,4,1,0.9);
INSERT INTO "TestNN_CONN" VALUES(0,5,2,0.6);
INSERT INTO "TestNN_CONN" VALUES(1,5,3,0.5);
INSERT INTO "TestNN_CONN" VALUES(2,5,4,-0.2);
INSERT INTO "TestNN_CONN" VALUES(3,2,0,0.2);
INSERT INTO "TestNN_CONN" VALUES(4,2,1,0.5);
INSERT INTO "TestNN_CONN" VALUES(5,3,0,0.8);
INSERT INTO "TestNN_CONN" VALUES(6,3,1,-0.3);
COMMIT;
